### PR TITLE
Add native tested modules of the Hexagon Toolkit

### PR DESCRIPTION
**Pull request by jaguililla**
* Native tests are checked in the nightly build against 'develop' branch
* Not all modules contains native image metadata, in that case, 'metadata_locations' is not included

## What does this PR do?
Add native tested modules of the Hexagon Toolkit

## Checklist before merging
- [x] I have considered including reachability metadata directly in the library or the framework (see [our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md))
- [x] I am the original author of all content provided in the pull request, and I did not copy the content from any other source (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [x] For all tests where I am not the sole author, I have added a comment that proves I may publish them under the specified license (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [x] I have properly formatted metadata files (see [our formatting guide](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#format-metadata-files))
- [x] I have added thorough tests (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))
- [x] I have filled all places where my pull request accesses files, network, docker, or any other external service (see the section above)

### CODE REVIEW

**Comment by fniephaus** [comment]
Hi @jaguililla, thanks for the PR. While we are reviewing your entries, could you please ensure the JSON remains sorted? This will also fix the failing build job. Thanks!

**Comment by jaguililla** [comment]
> Hi @jaguililla, thanks for the PR. While we are reviewing your entries, could you please ensure the JSON remains sorted? This will also fix the failing build job. Thanks!

Ok, I'll fix that, that for noticing me!

**Comment by fniephaus** [comment]
Thanks for sorting! `metadata_locations` is a required field because we want to make sure contributors have thought about this. For libraries that do not need metadata, I think you should be able to add an empty list via `metadata_locations: [],`. Could you take care of this please?

**Comment by jaguililla** [comment]
Done

**Comment by jaguililla** [comment]
I'm getting this error:

```
library-and-framework-list.json::$[5].artifact: 'com.hexagonkt:http_client' does not match '^[a-zA-Z0-9.-]+:[a-zA-Z0-9.-]+$'
```

However underscores are valid characters for artifacts' IDs and the toolkit libraries are published with those names.

Is there any way I can solve this validation problem without changing the artifacts' names?

**Comment by fniephaus** [comment]
I accidentally closed this PR by pushing the wrong branch. I've opened #411 with the right commits. Sorry for the inconvenience!

**Comment by jaguililla** [comment]
No worries

**Pull request closed without merging**
