### PR TITLE
Restrict Github Actions Jobs from being executed on Forked branches

### PR DESCRIPTION
**Pull request by linghengqian**
## What does this PR do?

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/226 .

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [x] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
- I think we can ignore CI errors from https://github.com/oracle/graalvm-reachability-metadata/actions/runs/4171153866/jobs/7220820491. It looks like Spring Framework is not compatible with GraalVM CE 23.0 Dev.

**Comment by fniephaus** [comment]
I don't understand why you want the workflows to be disabled in forked branches. This means you can only test your branch when you open a PR against this repo, right?

**Comment by linghengqian** [comment]
> I don't understand why you want the workflows to be disabled in forked branches. This means you can only test your branch when you open a PR against this repo, right?

- Yes, as usual for ASF Projects, CI Jobs including nightly builds should only happen in the main repository, because in most cases CI involves surprisingly large jobs. If users wish to run CI testing on a fork, they should individually modify the Github Actions file to turn on the specific CI.
- Executing a complete CI on a Fork branch with unresolved errors is very likely to receive double email reminders, which will also cause confusion for users.

**Review by fniephaus — APPROVED** [review]
LGTM. I don't see a reason why we shouldn't include this. The tests will still run as part of PRs for the main repo.

**Comment by linghengqian** [comment]
@fniephaus I checked https://github.com/oracle/graalvm-reachability-metadata/actions/runs/4235832275 and it looks like Gradle has no plans to add support for JDK20 now.  Does this require opening a new issue?

**Comment by fniephaus** [comment]
We are temporarily [disabling dev builds again](https://github.com/oracle/graalvm-reachability-metadata/pull/241) until the JDK17-based builds are back.

**Pull request merged**
