### PR TITLE
Added metadata for com.microsoft.sqlserver:mssql-jdbc

### PR DESCRIPTION
**Pull request by msupic**
## What does this PR do?
Added metadata for `com.microsoft.sqlserver:mssql-jdbc:12.2.0.jre11`

## Checklist before merging
- [ ] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [ ] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Comment by dnestoro** [comment]
Since this test uses `docker` it will be good that its merging waits until [this](https://github.com/oracle/graalvm-reachability-metadata/pull/240) PR is merged.

**Comment by graemerocher** [comment]
Can you prioritize this and #240?

**Comment by dnestoro** [comment]
> Can you prioritize this and #240?

Yes, I am waiting for an approval for one third party library, to be able to merge #240 PR. Once I get the approval, we will proceed with merging both PRs.

**Comment by msupic** [comment]
This PR depends on https://github.com/oracle/graalvm-reachability-metadata/pull/252

**Review by gradinac — APPROVED** [review]

**Pull request merged**
