### PR TITLE
Add support for `org.apache.commons:commons-dbcp2:2.9.0`

### PR DESCRIPTION
**Pull request by linghengqian**
## What does this PR do?

- Fixes https://github.com/oracle/graalvm-reachability-metadata/issues/202 .
- Closed some tests due to https://github.com/oracle/graal/issues/5913 .

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [x] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Comment by linghengqian** [comment]
- Call @vjovanov to help with the review.

**Comment by vjovanov** [comment]
@linghengqian there are a lot of tests in this PR. Did you write all of those tests, or they were copied from somewhere? 

Also, is it possible to have the same coverage of metadata with fewer tests?

**Comment by linghengqian** [comment]
> @linghengqian there are a lot of tests in this PR. Did you write all of those tests, or they were copied from somewhere? 
> 
> Also, is it possible to have the same coverage of metadata with fewer tests?

- Most of the tests are adapted from DBCP2's documentation and Git repository, and avoid the unit test suite that GraalVM does not support.  

- I covered most of the use cases where reducing the size of the unit test may lead to a future issue that requires building a more complex unit test.

- I assume you know which unit tests can be deleted directly? The unit tests here are considered before by the unit test rate.

**Comment by linghengqian** [comment]
- Late reply as I am busy these months. I will refactor the contents of this PR as required by the master branch. Until the refactoring is complete, the PR will be in a draft state.

**Review by linghengqian — COMMENTED** [review]
- Fixes on https://github.com/oracle/graalvm-reachability-metadata/pull/380 .

**Pull request closed without merging**
