### PR TITLE
Update library-and-framework-list.json with OCI APM Related details

### PR DESCRIPTION
**Pull request by smutalik**
## Checklist before merging
- [x] I have considered including reachability metadata directly in the library or the framework (see [this](./CONTRIBUTING.md))
- [x] I have properly formatted metadata files (see [this](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#format-metadata-files))
- [x] I have added thorough tests (see [this](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Review by fniephaus — APPROVED** [review]
LGTM, thank you!

**Review by fniephaus — CHANGES_REQUESTED** [review]
The JSON check fails because the entries are not sorted. Could you please make sure the JSON is sorted alphabetically?

**Comment by smutalik** [comment]
@fniephaus - I have updated the PR with the alphabetically sorted JSON file.

**Review by fniephaus — APPROVED** [review]
Thank you! LGTM and passes the relevant gate. The failing check is unrelated, we should get that fixed very soon.

**Pull request merged**
