### PR TITLE
Added metadata for com.github.ladutsko:isbn-core

### PR DESCRIPTION
**Pull request by ladutsko**
## What does this PR do?
Added metadata for com.github.ladutsko:isbn-core:1.2.0

## Checklist before merging
- [X] I have considered including reachability metadata directly in the library or the framework (see [this](./CONTRIBUTING.md))
- [X] I have properly formatted metadata files (see [this](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#format-metadata-files))
- [X] I have added thorough tests (see [this](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Review by bclozel — CHANGES_REQUESTED** [review]
Looks good to me!

Could you revisit the metadata to add [conditional configuration](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-reflection-metadata-in-json) to all your entries? It's [listed in the contributing checklist](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#checklist) but it looks like it's missing from the PR template?

For this case, adding the following to each entry should work:

```json
"condition": {
    "typeReachable": "com.github.ladutsko.isbn.ISBN"
},
```

**Comment by ladutsko** [comment]
@bclozel Thanks a lot!
I added conditional configuration and remove unused import.
Should I also add conditional configuration directly in the library?

**Comment by bclozel** [comment]
@ladutsko Wow sorry I just realized that the metadata [is already present at the library level](https://github.com/ladutsko/isbn-core/tree/master/src/main/resources/META-INF/native-image/com.github.ladutsko/isbn-core). I think this means that this PR is not needed. Reachability metadata is only meant for libraries where maintainers do not want to manage metadata, or where libraries were released before GraalVM existed.

In your case, adding the conditional configuration to the metadata in your library is enough! Managing metadata in your library is really the best option because you're keeping full control. Given the extent of your test suite, you might be able as well to use [a github action](https://github.com/marketplace/actions/github-action-for-graalvm) and run your entire test suite in native mode. @fniephaus is there a page or a sample project that shows how to set up a native image test suite for your own library? I guess the github action is the best course of action?

**Comment by fniephaus** [comment]
> is there a page or a sample project that shows how to set up a native image test suite for your own library?

I don't think there is a sample project yet, maybe file a ticket so we can work on one if you think that makes sense? There are, however, plenty of real world examples in [library-and-framework-list.json](https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list.json).

> I guess the github action is the best course of action?

For open source projects on GitHub, GitHub actions seems like a good idea, yes.

**Comment by ladutsko** [comment]
@bclozel
I will close this pr
should I create new pr to update [library-and-framework-list.json](https://github.com/oracle/graalvm-reachability-metadata/blob/master/library-and-framework-list.json)?
I would just like to highlight information about my library [here](https://www.graalvm.org/native-image/libraries-and-frameworks/)
Is native tests required in my repository in this case?

**Comment by bclozel** [comment]
Yes you can close this PR and submit another one for the official list on the site. If you are manually testing your library I guess it will be marked as "community tested". If you have a native test suite it will be marked as "fully tested".

**Comment by ladutsko** [comment]
@bclozel Thanks a lot for your support!

**Pull request closed without merging**
