### PR TITLE
add apache/rocketmq docker images

### PR DESCRIPTION
**Pull request by yuluo-yx**
## What does this PR do?

- For https://github.com/oracle/graalvm-reachability-metadata/issues/260
- For https://github.com/oracle/graalvm-reachability-metadata/pull/338
 
 ✔ Vulnerability DB        [no update available]
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [329 packages]
 ✔ Scanning image...       [1170 vulnerabilities]
   ├── 23 critical, 48 high, 496 medium, 599 low, 0 negligible (4 unknown)
   └── 141 fixed

### CODE REVIEW

**Comment by dnestoro** [comment]
@yuluo-yx only docker images without `critical` vulnerabilities and with only few `high` vulnerabilities can be considered as allowed (some more checks will be performed). Images that do not meet these requirements, will not be considered further

**Comment by dnestoro** [comment]
@yuluo-yx  Same as on your other [PR](https://github.com/oracle/graalvm-reachability-metadata/pull/321), if there is no progress in finding a new docker image, please close this PR since it cannot be merged with the current state. If you can find image with less vulnerabilities, please change it in the PR and update the description with the report for the new image

**Comment by dnestoro** [comment]
@yuluo-yx If there are no changes, please close this PR

**Comment by yuluo-yx** [comment]
> @yuluo-yx If there are no changes, please close this PR

done!

**Pull request closed without merging**
