### PR TITLE
Fix a typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by linghengqian**
## What does this PR do?

- Fix a typo in CONTRIBUTING.md .
- For https://github.com/oracle/graalvm-reachability-metadata/pull/97 .

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [ ] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Comment by mhalbritter** [comment]
The lowercase "in" is correct in this case, i think.

**Comment by linghengqian** [comment]
- That looks like I misunderstood, and I'll close this PR.

> The lowercase "in" is correct in this case, i think.

**Comment by mhalbritter** [comment]
But it looks like there is a useless linebreak, which braks the NOTE block. This should be fixed.

**Comment by linghengqian** [comment]
> But it looks like there is a useless linebreak, which braks the NOTE block. This should be fixed.

- I reprocessed it.

**Review by dnestoro — APPROVED** [review]

**Pull request merged**
