### PR TITLE
Enable override attribute on Netty dependencies

### PR DESCRIPTION
**Pull request by sdeleuze**
@gradinac Could you please review this PR? We should also probably update the repository version to `0.2.0-SNAPSHOT` in order to express that the format has changed.

### CODE REVIEW

**Comment by sdeleuze** [comment]
I had to include empty metadata to override Netty configurations, should I add empty tests or do we have a way to exclude those for the checks?

**Comment by lazar-mitrovic** [comment]
I would personally prefer if we had explicit tests for each part of Netty (especially since we are now excluding existing config, and we should check for regressions).

Alternatively we could link it to the existing `netty-transport` test or some dummy test, but I'm afraid that would set a bad precedent.

**Comment by lazar-mitrovic** [comment]
- [ ] Prior to merging this we need to implement `override` support for TCK in order to be able to properly test metadata.
This shouldn't be hard, fix shouldn't be more than couple of lines long. I'll take a look at that this week.

**Comment by sdeleuze** [comment]
To add some tests, don't we need NBT 0.9.14 to be released first? Isn't it a kind of chicken and egg problem?

**Comment by lazar-mitrovic** [comment]
> To add some tests, don't we need NBT 0.9.14 to be released first? Isn't it a kind of chicken and egg problem? If so we can maybe more forward with empty tests for now and add proper testing as a second step after NBT 0.9.14 and metadata repo 0.2.0 releases.

Well, we already have a different code path for metadata location detection [here](https://github.com/oracle/graalvm-reachability-metadata/blob/bb36403180544e182008266edc9340f37c1a4fcb/tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck.gradle#L72). We aren't using metadata support artifact here since it isn't what we are testing - we are just using standard primitives and relying on TCK to inject the right values for us, and thus we don't rely on NBT version at all.

**Comment by sdeleuze** [comment]
Ok please let me know when you have done the required update, I can then add related tests (unless you want to do it).

**Comment by sdeleuze** [comment]
Rebased on top of the commit mentioned in [this comment](https://github.com/oracle/graalvm-reachability-metadata/pull/52#issuecomment-1250327355) and after various tries, I decided to skip tests for empty metadata.

**Pull request merged**
