### PR TITLE
Add 'scaffold' task to generate metadata and tests for a library

### LINKED ISSUE #88: Improve configuration files to avoid duplicating information
Currently one needs to create a lot of JSON files with duplicate information. Take for example the undertow tests. The version is in:

* `metadata/io.undertow/undertow-core/index.json` twice
* `tests/src/index.json` twice
* `tests/src/io.undertow/undertow-core/2.2.19.Final/gradle.properties` twice

The coordinates without the version are in even more files (in addition to the files mentioned above):

* `metadata/index.json`

Could we find a way to not duplicate this information all over the place? If that's not possible, we should create a Gradle task which takes the coordinates (`io.undertow:undertow-core:2.2.19.Final` in this case) and creates all the necessary JSON entries. As it is right now it's quite a chore to setup the metadata for a new dependency.

### PR DESCRIPTION
**Pull request by mhalbritter**
## What does this PR do?

Adds a task to create metadata and tests.

Run with `gradle scaffold --coordinates com.example:my-library:1.0.0`.

Closes #88.

### CODE REVIEW

**Comment by mhalbritter** [comment]
The CI is broken as it uses the default java version (which is not 17). I used java 17 features in the task. See https://github.com/oracle/graalvm-reachability-metadata/pull/97/commits/9a74417813fdda3b2337c47e8ebbc827f8fcc10d

**Comment by sdeleuze** [comment]
Looks great.

**Comment by sdeleuze** [comment]
> The CI is broken as it uses the default java version (which is not 17). I used java 17 features in the task. See https://github.com/oracle/graalvm-reachability-metadata/commit/9a74417813fdda3b2337c47e8ebbc827f8fcc10d

@mhalbritter I am not sure to understand why the CI is broken despite 9a74417813fdda3b2337c47e8ebbc827f8fcc10d, and I don't think it will be merged until this is fixed. Could you please elaborate on this?

**Comment by mhalbritter** [comment]
Yes, this is my understanding, but I'm confused why my change from https://github.com/oracle/graalvm-reachability-metadata/commit/9a74417813fdda3b2337c47e8ebbc827f8fcc10d isn't applied to this PRs pipeline.

**Comment by fniephaus** [comment]
@mhalbritter can you try with [`setup-graalvm`](https://github.com/graalvm/setup-graalvm)? It'd be great if as many GraalVM bits as possible are tested with GraalVM JDK.

**Comment by mhalbritter** [comment]
I've update the CI to use `setup-graalvm`. The CI still fails, and now I'm quite sure that the CI takes the config from `master`, as there's a 3rd step ("Validate library and framework list"), which is not in my branch.

**Comment by fniephaus** [comment]
The CI should be trying to build the merge of this PR into master. It seems that the JSON validating job fails because it's using a JDK that doesn't support records?

**Comment by fniephaus** [comment]
I've rebased your branch and added https://github.com/oracle/graalvm-reachability-metadata/pull/97/commits/77203858848b20d848e783a5ae2ac9c4fe1f77ae and, more importantly, https://github.com/oracle/graalvm-reachability-metadata/pull/97/commits/67a706173054c3d3f55b0c9e5a3147ecd423ca17.

**Comment by fniephaus** [comment]
I've rebased your branch and added https://github.com/oracle/graalvm-reachability-metadata/pull/97/commits/f3d052df653ccfcc4e6b403e97c7735f50853376 and a few other commits.

**Comment by fniephaus** [comment]
Ok, now this is blocked by missing permissions...let me get that fixed...

**Comment by linghengqian** [comment]
- I'm just curious, after the current PR is merged, will another PR modify the content of [CONTINBUTING. md](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) ?

**Comment by fniephaus** [comment]
>Ok, now this is blocked by missing permissions...let me get that fixed...

That's now working.

**Comment by mhalbritter** [comment]
I've squashed the commits and the CI is green, too. Ready to merge from my side.

**Review by fniephaus — APPROVED** [review]
LGTM. Can this be merged, @dnestoro?

**Review by dnestoro — APPROVED** [review]

**Comment by dnestoro** [comment]
I will merge this PR, but just one note: I refactored usage of coordinates across the project with this pr #54. Once that PR is ready to be merged, I will probably refactor some parts here as well.

**Comment by mhalbritter** [comment]
> I'm just curious, after the current PR is merged, will another PR modify the content of [CONTINBUTING.md](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) ?

I've updated the CONTRIBUTING.md.

**Pull request merged**
