### PR TITLE
Add config for hibernate-validator

### PR DESCRIPTION
**Pull request by mhalbritter**
Signed-off-by: Moritz Halbritter <mkammerer@vmware.com>

## What does this PR do?

Adds metadata for hibernate validator. The readme in the tests explains how these files have been generated.

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [x] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Review by lazar-mitrovic — CHANGES_REQUESTED** [review]
It seems that you are missing `metadata/index.json` entry for this library.
This won't be necessary after #1 is merged, but for now tests won't be triggered unless this is fixed.

**Comment by mhalbritter** [comment]
Thanks. I have updated the PR.

**Comment by mhalbritter** [comment]
Ah, i used Java 17 features. I will update to only use Java 11 features.

**Comment by mhalbritter** [comment]
Done, please approve to let the CI run, thanks :)

**Review by lazar-mitrovic — APPROVED** [review]

**Comment by mhalbritter** [comment]
Thanks!

**Pull request merged**
