### PR TITLE
Add support for Testcontainers

### LINKED ISSUE #129: Add support for testcontainers
Please add support for `org.testcontainers:testcontainers:1.17.6`.

Depends on #128.

### PR DESCRIPTION
**Pull request by mhalbritter**
## What does this PR do?

Adds metadata for testcontainers.

Closes #129.

This PR builds on top of the JNA one (#130), so please merge #130 before this.

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [x] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Review by dnestoro — APPROVED** [review]

**Comment by cforce** [comment]
Tested and works -Please release!

**Comment by linghengqian** [comment]
> Tested and works -Please release . I still can't see the change at master https://github.com/oracle/graalvm-reachability-metadata/blob/master/metadata/org.testcontainers/testcontainers/1.17.6/resource-config.json

- I assume someone can review and merge #116, #121, #124, #127 and #135 .  It is a pain for me to maintain multiple PR updates to the master branch at the same time.:-(

**Comment by dnestoro** [comment]
We plan to review the PRs (merge the good ones) and make a release next week.

**Comment by dnestoro** [comment]
> We plan to review the PRs (merge the good ones) and make a release next week.

@linghengqian Since many of your PRs needs a bit of work, we will postpone the release for next week, since we don't have enough material for the new release.

**Pull request merged**
