### PR TITLE
Add Neo4j-Java-Driver to `library-and-framework-list.json`.

### PR DESCRIPTION
**Pull request by michael-simons**
## What does this PR do?

This adds the Neo4j-Java-Driver to the list of tested libraries and frameworks.
We use the linked repository in CI, testing all currently maintained versions of the driver.

## Checklist before merging
- [x] I have properly formatted metadata files (see [CONTRIBUTING](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md) document)
- [ ] I have added thorough tests. (see [this](/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks a lot for the PR, @michael-simons! Do these [`neo4j-java-driver-native-smoke-tests`](https://github.com/neo4j-drivers/neo4j-java-driver-native-smoke-tests) run regularly on some CI system? If so, it'd be great if you could add a link to the `tests_locations`.

**Comment by michael-simons** [comment]
My pleasure and indeed they do. @injectives do you if we can publish the result to the repo or the main driver repo?

**Comment by fniephaus** [comment]
@michael-simons any update on this? We're soon going to publish a list based on this JSON file and I'd like to merge this asap. I'm happy to merge this now if we flag the library as community-tested, or fully-tested if you provide an appropriate test location.

**Comment by michael-simons** [comment]
Hej.

You see the test results on each PR to the official driver repo, i.e.

https://github.com/neo4j/neo4j-java-driver/pull/1352

image

Stuff is hidden behind the details button going with the merge commit…

This is fully tested and the addition to the list is not really different than let's say the Helidon ones.

**Review by fniephaus — APPROVED** [review]

**Comment by michael-simons** [comment]
My pleasure and thanks for including us!

**Pull request merged**
